// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/v1/heimdall.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_api_v1_heimdall_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_heimdall_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_heimdall_proto_rawDescGZIP(), []int{0}
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locked        bool                   `protobuf:"varint,1,opt,name=locked,proto3" json:"locked,omitempty"`
	HasLiveVmk    bool                   `protobuf:"varint,2,opt,name=has_live_vmk,json=hasLiveVmk,proto3" json:"has_live_vmk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_api_v1_heimdall_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_heimdall_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_heimdall_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResponse) GetLocked() bool {
	if x != nil {
		return x.Locked
	}
	return false
}

func (x *StatusResponse) GetHasLiveVmk() bool {
	if x != nil {
		return x.HasLiveVmk
	}
	return false
}

type LockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockRequest) Reset() {
	*x = LockRequest{}
	mi := &file_api_v1_heimdall_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockRequest) ProtoMessage() {}

func (x *LockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_heimdall_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockRequest.ProtoReflect.Descriptor instead.
func (*LockRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_heimdall_proto_rawDescGZIP(), []int{2}
}

type LockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockResponse) Reset() {
	*x = LockResponse{}
	mi := &file_api_v1_heimdall_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockResponse) ProtoMessage() {}

func (x *LockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_heimdall_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockResponse.ProtoReflect.Descriptor instead.
func (*LockResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_heimdall_proto_rawDescGZIP(), []int{3}
}

type GetVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionRequest) Reset() {
	*x = GetVersionRequest{}
	mi := &file_api_v1_heimdall_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionRequest) ProtoMessage() {}

func (x *GetVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_heimdall_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionRequest.ProtoReflect.Descriptor instead.
func (*GetVersionRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_heimdall_proto_rawDescGZIP(), []int{4}
}

type GetVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Commit        string                 `protobuf:"bytes,2,opt,name=commit,proto3" json:"commit,omitempty"`
	BuildTime     string                 `protobuf:"bytes,3,opt,name=build_time,json=buildTime,proto3" json:"build_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionResponse) Reset() {
	*x = GetVersionResponse{}
	mi := &file_api_v1_heimdall_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionResponse) ProtoMessage() {}

func (x *GetVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_heimdall_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionResponse.ProtoReflect.Descriptor instead.
func (*GetVersionResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_heimdall_proto_rawDescGZIP(), []int{5}
}

func (x *GetVersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetVersionResponse) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *GetVersionResponse) GetBuildTime() string {
	if x != nil {
		return x.BuildTime
	}
	return ""
}

type ListHostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NamesOnly     bool                   `protobuf:"varint,1,opt,name=names_only,json=namesOnly,proto3" json:"names_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHostsRequest) Reset() {
	*x = ListHostsRequest{}
	mi := &file_api_v1_heimdall_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHostsRequest) ProtoMessage() {}

func (x *ListHostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_heimdall_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHostsRequest.ProtoReflect.Descriptor instead.
func (*ListHostsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_heimdall_proto_rawDescGZIP(), []int{6}
}

func (x *ListHostsRequest) GetNamesOnly() bool {
	if x != nil {
		return x.NamesOnly
	}
	return false
}

type Host struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Port          int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	User          string                 `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Host) Reset() {
	*x = Host{}
	mi := &file_api_v1_heimdall_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Host) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Host) ProtoMessage() {}

func (x *Host) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_heimdall_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Host.ProtoReflect.Descriptor instead.
func (*Host) Descriptor() ([]byte, []int) {
	return file_api_v1_heimdall_proto_rawDescGZIP(), []int{7}
}

func (x *Host) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Host) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Host) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Host) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Host) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *Host) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ListHostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hosts         []*Host                `protobuf:"bytes,1,rep,name=hosts,proto3" json:"hosts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHostsResponse) Reset() {
	*x = ListHostsResponse{}
	mi := &file_api_v1_heimdall_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHostsResponse) ProtoMessage() {}

func (x *ListHostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_heimdall_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHostsResponse.ProtoReflect.Descriptor instead.
func (*ListHostsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_heimdall_proto_rawDescGZIP(), []int{8}
}

func (x *ListHostsResponse) GetHosts() []*Host {
	if x != nil {
		return x.Hosts
	}
	return nil
}

type ListSecretsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsRequest) Reset() {
	*x = ListSecretsRequest{}
	mi := &file_api_v1_heimdall_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsRequest) ProtoMessage() {}

func (x *ListSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_heimdall_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsRequest.ProtoReflect.Descriptor instead.
func (*ListSecretsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_heimdall_proto_rawDescGZIP(), []int{9}
}

type SecretMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RevealPolicy  string                 `protobuf:"bytes,3,opt,name=reveal_policy,json=revealPolicy,proto3" json:"reveal_policy,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretMeta) Reset() {
	*x = SecretMeta{}
	mi := &file_api_v1_heimdall_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretMeta) ProtoMessage() {}

func (x *SecretMeta) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_heimdall_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretMeta.ProtoReflect.Descriptor instead.
func (*SecretMeta) Descriptor() ([]byte, []int) {
	return file_api_v1_heimdall_proto_rawDescGZIP(), []int{10}
}

func (x *SecretMeta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SecretMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SecretMeta) GetRevealPolicy() string {
	if x != nil {
		return x.RevealPolicy
	}
	return ""
}

func (x *SecretMeta) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type ListSecretsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secrets       []*SecretMeta          `protobuf:"bytes,1,rep,name=secrets,proto3" json:"secrets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsResponse) Reset() {
	*x = ListSecretsResponse{}
	mi := &file_api_v1_heimdall_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsResponse) ProtoMessage() {}

func (x *ListSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_heimdall_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsResponse.ProtoReflect.Descriptor instead.
func (*ListSecretsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_heimdall_proto_rawDescGZIP(), []int{11}
}

func (x *ListSecretsResponse) GetSecrets() []*SecretMeta {
	if x != nil {
		return x.Secrets
	}
	return nil
}

type GetSecretValueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretValueRequest) Reset() {
	*x = GetSecretValueRequest{}
	mi := &file_api_v1_heimdall_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretValueRequest) ProtoMessage() {}

func (x *GetSecretValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_heimdall_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretValueRequest.ProtoReflect.Descriptor instead.
func (*GetSecretValueRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_heimdall_proto_rawDescGZIP(), []int{12}
}

func (x *GetSecretValueRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetSecretValueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretValueResponse) Reset() {
	*x = GetSecretValueResponse{}
	mi := &file_api_v1_heimdall_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretValueResponse) ProtoMessage() {}

func (x *GetSecretValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_heimdall_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretValueResponse.ProtoReflect.Descriptor instead.
func (*GetSecretValueResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_heimdall_proto_rawDescGZIP(), []int{13}
}

func (x *GetSecretValueResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type DeleteSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretRequest) Reset() {
	*x = DeleteSecretRequest{}
	mi := &file_api_v1_heimdall_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretRequest) ProtoMessage() {}

func (x *DeleteSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_heimdall_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretRequest.ProtoReflect.Descriptor instead.
func (*DeleteSecretRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_heimdall_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteSecretRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretResponse) Reset() {
	*x = DeleteSecretResponse{}
	mi := &file_api_v1_heimdall_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretResponse) ProtoMessage() {}

func (x *DeleteSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_heimdall_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretResponse.ProtoReflect.Descriptor instead.
func (*DeleteSecretResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_heimdall_proto_rawDescGZIP(), []int{15}
}

type UploadChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RevealPolicy  string                 `protobuf:"bytes,2,opt,name=reveal_policy,json=revealPolicy,proto3" json:"reveal_policy,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Eof           bool                   `protobuf:"varint,4,opt,name=eof,proto3" json:"eof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadChunk) Reset() {
	*x = UploadChunk{}
	mi := &file_api_v1_heimdall_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadChunk) ProtoMessage() {}

func (x *UploadChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_heimdall_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadChunk.ProtoReflect.Descriptor instead.
func (*UploadChunk) Descriptor() ([]byte, []int) {
	return file_api_v1_heimdall_proto_rawDescGZIP(), []int{16}
}

func (x *UploadChunk) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UploadChunk) GetRevealPolicy() string {
	if x != nil {
		return x.RevealPolicy
	}
	return ""
}

func (x *UploadChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UploadChunk) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

type UploadFileSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        *SecretMeta            `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileSecretResponse) Reset() {
	*x = UploadFileSecretResponse{}
	mi := &file_api_v1_heimdall_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileSecretResponse) ProtoMessage() {}

func (x *UploadFileSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_heimdall_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileSecretResponse.ProtoReflect.Descriptor instead.
func (*UploadFileSecretResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_heimdall_proto_rawDescGZIP(), []int{17}
}

func (x *UploadFileSecretResponse) GetSecret() *SecretMeta {
	if x != nil {
		return x.Secret
	}
	return nil
}

type DownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ChunkSize     int32                  `protobuf:"varint,2,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	mi := &file_api_v1_heimdall_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_heimdall_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_heimdall_proto_rawDescGZIP(), []int{18}
}

func (x *DownloadRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DownloadRequest) GetChunkSize() int32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

type DownloadChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Eof           bool                   `protobuf:"varint,2,opt,name=eof,proto3" json:"eof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadChunk) Reset() {
	*x = DownloadChunk{}
	mi := &file_api_v1_heimdall_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadChunk) ProtoMessage() {}

func (x *DownloadChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_heimdall_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadChunk.ProtoReflect.Descriptor instead.
func (*DownloadChunk) Descriptor() ([]byte, []int) {
	return file_api_v1_heimdall_proto_rawDescGZIP(), []int{19}
}

func (x *DownloadChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DownloadChunk) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

type ExportKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportKeyRequest) Reset() {
	*x = ExportKeyRequest{}
	mi := &file_api_v1_heimdall_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportKeyRequest) ProtoMessage() {}

func (x *ExportKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_heimdall_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportKeyRequest.ProtoReflect.Descriptor instead.
func (*ExportKeyRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_heimdall_proto_rawDescGZIP(), []int{20}
}

func (x *ExportKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ExportKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	KeyType       string                 `protobuf:"bytes,2,opt,name=key_type,json=keyType,proto3" json:"key_type,omitempty"`
	PublicKey     string                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	PrivateKey    []byte                 `protobuf:"bytes,4,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportKeyResponse) Reset() {
	*x = ExportKeyResponse{}
	mi := &file_api_v1_heimdall_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportKeyResponse) ProtoMessage() {}

func (x *ExportKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_heimdall_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportKeyResponse.ProtoReflect.Descriptor instead.
func (*ExportKeyResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_heimdall_proto_rawDescGZIP(), []int{21}
}

func (x *ExportKeyResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExportKeyResponse) GetKeyType() string {
	if x != nil {
		return x.KeyType
	}
	return ""
}

func (x *ExportKeyResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *ExportKeyResponse) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

type ListPasskeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPasskeysRequest) Reset() {
	*x = ListPasskeysRequest{}
	mi := &file_api_v1_heimdall_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPasskeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPasskeysRequest) ProtoMessage() {}

func (x *ListPasskeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_heimdall_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPasskeysRequest.ProtoReflect.Descriptor instead.
func (*ListPasskeysRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_heimdall_proto_rawDescGZIP(), []int{22}
}

type PasskeyMeta struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Label              string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	SupportsHmacSecret bool                   `protobuf:"varint,3,opt,name=supports_hmac_secret,json=supportsHmacSecret,proto3" json:"supports_hmac_secret,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PasskeyMeta) Reset() {
	*x = PasskeyMeta{}
	mi := &file_api_v1_heimdall_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasskeyMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasskeyMeta) ProtoMessage() {}

func (x *PasskeyMeta) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_heimdall_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasskeyMeta.ProtoReflect.Descriptor instead.
func (*PasskeyMeta) Descriptor() ([]byte, []int) {
	return file_api_v1_heimdall_proto_rawDescGZIP(), []int{23}
}

func (x *PasskeyMeta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PasskeyMeta) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *PasskeyMeta) GetSupportsHmacSecret() bool {
	if x != nil {
		return x.SupportsHmacSecret
	}
	return false
}

type ListPasskeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Passkeys      []*PasskeyMeta         `protobuf:"bytes,1,rep,name=passkeys,proto3" json:"passkeys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPasskeysResponse) Reset() {
	*x = ListPasskeysResponse{}
	mi := &file_api_v1_heimdall_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPasskeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPasskeysResponse) ProtoMessage() {}

func (x *ListPasskeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_heimdall_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPasskeysResponse.ProtoReflect.Descriptor instead.
func (*ListPasskeysResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_heimdall_proto_rawDescGZIP(), []int{24}
}

func (x *ListPasskeysResponse) GetPasskeys() []*PasskeyMeta {
	if x != nil {
		return x.Passkeys
	}
	return nil
}

type ForwardSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	Spec          string                 `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardSpec) Reset() {
	*x = ForwardSpec{}
	mi := &file_api_v1_heimdall_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardSpec) ProtoMessage() {}

func (x *ForwardSpec) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_heimdall_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardSpec.ProtoReflect.Descriptor instead.
func (*ForwardSpec) Descriptor() ([]byte, []int) {
	return file_api_v1_heimdall_proto_rawDescGZIP(), []int{25}
}

func (x *ForwardSpec) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *ForwardSpec) GetSpec() string {
	if x != nil {
		return x.Spec
	}
	return ""
}

type PlanConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostName      string                 `protobuf:"bytes,1,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	JumpHosts     []string               `protobuf:"bytes,4,rep,name=jump_hosts,json=jumpHosts,proto3" json:"jump_hosts,omitempty"`
	Forwards      []string               `protobuf:"bytes,5,rep,name=forwards,proto3" json:"forwards,omitempty"`
	IdentityPath  string                 `protobuf:"bytes,6,opt,name=identity_path,json=identityPath,proto3" json:"identity_path,omitempty"`
	KnownHosts    string                 `protobuf:"bytes,7,opt,name=known_hosts,json=knownHosts,proto3" json:"known_hosts,omitempty"`
	PrintCmd      bool                   `protobuf:"varint,8,opt,name=print_cmd,json=printCmd,proto3" json:"print_cmd,omitempty"`
	DryRun        bool                   `protobuf:"varint,9,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanConnectRequest) Reset() {
	*x = PlanConnectRequest{}
	mi := &file_api_v1_heimdall_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanConnectRequest) ProtoMessage() {}

func (x *PlanConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_heimdall_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanConnectRequest.ProtoReflect.Descriptor instead.
func (*PlanConnectRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_heimdall_proto_rawDescGZIP(), []int{26}
}

func (x *PlanConnectRequest) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *PlanConnectRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *PlanConnectRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *PlanConnectRequest) GetJumpHosts() []string {
	if x != nil {
		return x.JumpHosts
	}
	return nil
}

func (x *PlanConnectRequest) GetForwards() []string {
	if x != nil {
		return x.Forwards
	}
	return nil
}

func (x *PlanConnectRequest) GetIdentityPath() string {
	if x != nil {
		return x.IdentityPath
	}
	return ""
}

func (x *PlanConnectRequest) GetKnownHosts() string {
	if x != nil {
		return x.KnownHosts
	}
	return ""
}

func (x *PlanConnectRequest) GetPrintCmd() bool {
	if x != nil {
		return x.PrintCmd
	}
	return false
}

func (x *PlanConnectRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

type SSHCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Binary        string                 `protobuf:"bytes,1,opt,name=binary,proto3" json:"binary,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	RedactedArgs  []string               `protobuf:"bytes,3,rep,name=redacted_args,json=redactedArgs,proto3" json:"redacted_args,omitempty"`
	Env           []string               `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty"`
	TempFiles     []string               `protobuf:"bytes,5,rep,name=temp_files,json=tempFiles,proto3" json:"temp_files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SSHCommand) Reset() {
	*x = SSHCommand{}
	mi := &file_api_v1_heimdall_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SSHCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSHCommand) ProtoMessage() {}

func (x *SSHCommand) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_heimdall_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSHCommand.ProtoReflect.Descriptor instead.
func (*SSHCommand) Descriptor() ([]byte, []int) {
	return file_api_v1_heimdall_proto_rawDescGZIP(), []int{27}
}

func (x *SSHCommand) GetBinary() string {
	if x != nil {
		return x.Binary
	}
	return ""
}

func (x *SSHCommand) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *SSHCommand) GetRedactedArgs() []string {
	if x != nil {
		return x.RedactedArgs
	}
	return nil
}

func (x *SSHCommand) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *SSHCommand) GetTempFiles() []string {
	if x != nil {
		return x.TempFiles
	}
	return nil
}

type PlanConnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       *SSHCommand            `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanConnectResponse) Reset() {
	*x = PlanConnectResponse{}
	mi := &file_api_v1_heimdall_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanConnectResponse) ProtoMessage() {}

func (x *PlanConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_heimdall_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanConnectResponse.ProtoReflect.Descriptor instead.
func (*PlanConnectResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_heimdall_proto_rawDescGZIP(), []int{28}
}

func (x *PlanConnectResponse) GetCommand() *SSHCommand {
	if x != nil {
		return x.Command
	}
	return nil
}

type ListEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsRequest) Reset() {
	*x = ListEventsRequest{}
	mi := &file_api_v1_heimdall_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequest) ProtoMessage() {}

func (x *ListEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_heimdall_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequest.ProtoReflect.Descriptor instead.
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_heimdall_proto_rawDescGZIP(), []int{29}
}

func (x *ListEventsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type AuditEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	TargetType    string                 `protobuf:"bytes,3,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	TargetId      string                 `protobuf:"bytes,4,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Result        string                 `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	DetailsJson   string                 `protobuf:"bytes,6,opt,name=details_json,json=detailsJson,proto3" json:"details_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditEvent) Reset() {
	*x = AuditEvent{}
	mi := &file_api_v1_heimdall_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEvent) ProtoMessage() {}

func (x *AuditEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_heimdall_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEvent.ProtoReflect.Descriptor instead.
func (*AuditEvent) Descriptor() ([]byte, []int) {
	return file_api_v1_heimdall_proto_rawDescGZIP(), []int{30}
}

func (x *AuditEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuditEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditEvent) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *AuditEvent) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *AuditEvent) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *AuditEvent) GetDetailsJson() string {
	if x != nil {
		return x.DetailsJson
	}
	return ""
}

type ListEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*AuditEvent          `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsResponse) Reset() {
	*x = ListEventsResponse{}
	mi := &file_api_v1_heimdall_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsResponse) ProtoMessage() {}

func (x *ListEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_heimdall_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsResponse.ProtoReflect.Descriptor instead.
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_heimdall_proto_rawDescGZIP(), []int{31}
}

func (x *ListEventsResponse) GetEvents() []*AuditEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type CreateBackupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBackupRequest) Reset() {
	*x = CreateBackupRequest{}
	mi := &file_api_v1_heimdall_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBackupRequest) ProtoMessage() {}

func (x *CreateBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_heimdall_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBackupRequest.ProtoReflect.Descriptor instead.
func (*CreateBackupRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_heimdall_proto_rawDescGZIP(), []int{32}
}

type CreateBackupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBackupResponse) Reset() {
	*x = CreateBackupResponse{}
	mi := &file_api_v1_heimdall_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBackupResponse) ProtoMessage() {}

func (x *CreateBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_heimdall_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBackupResponse.ProtoReflect.Descriptor instead.
func (*CreateBackupResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_heimdall_proto_rawDescGZIP(), []int{33}
}

func (x *CreateBackupResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type RecordSessionStartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostId        string                 `protobuf:"bytes,1,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordSessionStartRequest) Reset() {
	*x = RecordSessionStartRequest{}
	mi := &file_api_v1_heimdall_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordSessionStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordSessionStartRequest) ProtoMessage() {}

func (x *RecordSessionStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_heimdall_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordSessionStartRequest.ProtoReflect.Descriptor instead.
func (*RecordSessionStartRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_heimdall_proto_rawDescGZIP(), []int{34}
}

func (x *RecordSessionStartRequest) GetHostId() string {
	if x != nil {
		return x.HostId
	}
	return ""
}

func (x *RecordSessionStartRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type RecordSessionStartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordSessionStartResponse) Reset() {
	*x = RecordSessionStartResponse{}
	mi := &file_api_v1_heimdall_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordSessionStartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordSessionStartResponse) ProtoMessage() {}

func (x *RecordSessionStartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_heimdall_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordSessionStartResponse.ProtoReflect.Descriptor instead.
func (*RecordSessionStartResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_heimdall_proto_rawDescGZIP(), []int{35}
}

func (x *RecordSessionStartResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type RecordSessionEndRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ExitCode      int32                  `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordSessionEndRequest) Reset() {
	*x = RecordSessionEndRequest{}
	mi := &file_api_v1_heimdall_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordSessionEndRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordSessionEndRequest) ProtoMessage() {}

func (x *RecordSessionEndRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_heimdall_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordSessionEndRequest.ProtoReflect.Descriptor instead.
func (*RecordSessionEndRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_heimdall_proto_rawDescGZIP(), []int{36}
}

func (x *RecordSessionEndRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RecordSessionEndRequest) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type RecordSessionEndResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordSessionEndResponse) Reset() {
	*x = RecordSessionEndResponse{}
	mi := &file_api_v1_heimdall_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordSessionEndResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordSessionEndResponse) ProtoMessage() {}

func (x *RecordSessionEndResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_heimdall_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordSessionEndResponse.ProtoReflect.Descriptor instead.
func (*RecordSessionEndResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_heimdall_proto_rawDescGZIP(), []int{37}
}

type VerifyAssertionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	AuthData      []byte                 `protobuf:"bytes,2,opt,name=auth_data,json=authData,proto3" json:"auth_data,omitempty"`
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyAssertionRequest) Reset() {
	*x = VerifyAssertionRequest{}
	mi := &file_api_v1_heimdall_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyAssertionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAssertionRequest) ProtoMessage() {}

func (x *VerifyAssertionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_heimdall_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAssertionRequest.ProtoReflect.Descriptor instead.
func (*VerifyAssertionRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_heimdall_proto_rawDescGZIP(), []int{38}
}

func (x *VerifyAssertionRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *VerifyAssertionRequest) GetAuthData() []byte {
	if x != nil {
		return x.AuthData
	}
	return nil
}

func (x *VerifyAssertionRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type VerifyAssertionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyAssertionResponse) Reset() {
	*x = VerifyAssertionResponse{}
	mi := &file_api_v1_heimdall_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyAssertionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyAssertionResponse) ProtoMessage() {}

func (x *VerifyAssertionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_heimdall_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyAssertionResponse.ProtoReflect.Descriptor instead.
func (*VerifyAssertionResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_heimdall_proto_rawDescGZIP(), []int{39}
}

func (x *VerifyAssertionResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type VerifyPassphraseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Passphrase    string                 `protobuf:"bytes,1,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPassphraseRequest) Reset() {
	*x = VerifyPassphraseRequest{}
	mi := &file_api_v1_heimdall_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPassphraseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPassphraseRequest) ProtoMessage() {}

func (x *VerifyPassphraseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_heimdall_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPassphraseRequest.ProtoReflect.Descriptor instead.
func (*VerifyPassphraseRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_heimdall_proto_rawDescGZIP(), []int{40}
}

func (x *VerifyPassphraseRequest) GetPassphrase() string {
	if x != nil {
		return x.Passphrase
	}
	return ""
}

type VerifyPassphraseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPassphraseResponse) Reset() {
	*x = VerifyPassphraseResponse{}
	mi := &file_api_v1_heimdall_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPassphraseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPassphraseResponse) ProtoMessage() {}

func (x *VerifyPassphraseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_heimdall_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPassphraseResponse.ProtoReflect.Descriptor instead.
func (*VerifyPassphraseResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_heimdall_proto_rawDescGZIP(), []int{41}
}

func (x *VerifyPassphraseResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_api_v1_heimdall_proto protoreflect.FileDescriptor

const file_api_v1_heimdall_proto_rawDesc = "" +
	"\n" +
	"\x15api/v1/heimdall.proto\x12\vheimdall.v1\"\x0f\n" +
	"\rStatusRequest\"J\n" +
	"\x0eStatusResponse\x12\x16\n" +
	"\x06locked\x18\x01 \x01(\bR\x06locked\x12 \n" +
	"\fhas_live_vmk\x18\x02 \x01(\bR\n" +
	"hasLiveVmk\"\r\n" +
	"\vLockRequest\"\x0e\n" +
	"\fLockResponse\"\x13\n" +
	"\x11GetVersionRequest\"e\n" +
	"\x12GetVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06commit\x18\x02 \x01(\tR\x06commit\x12\x1d\n" +
	"\n" +
	"build_time\x18\x03 \x01(\tR\tbuildTime\"1\n" +
	"\x10ListHostsRequest\x12\x1d\n" +
	"\n" +
	"names_only\x18\x01 \x01(\bR\tnamesOnly\"\x80\x01\n" +
	"\x04Host\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12\x12\n" +
	"\x04user\x18\x05 \x01(\tR\x04user\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\"<\n" +
	"\x11ListHostsResponse\x12'\n" +
	"\x05hosts\x18\x01 \x03(\v2\x11.heimdall.v1.HostR\x05hosts\"\x14\n" +
	"\x12ListSecretsRequest\"t\n" +
	"\n" +
	"SecretMeta\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rreveal_policy\x18\x03 \x01(\tR\frevealPolicy\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\"H\n" +
	"\x13ListSecretsResponse\x121\n" +
	"\asecrets\x18\x01 \x03(\v2\x17.heimdall.v1.SecretMetaR\asecrets\"+\n" +
	"\x15GetSecretValueRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\".\n" +
	"\x16GetSecretValueResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\")\n" +
	"\x13DeleteSecretRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x16\n" +
	"\x14DeleteSecretResponse\"l\n" +
	"\vUploadChunk\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12#\n" +
	"\rreveal_policy\x18\x02 \x01(\tR\frevealPolicy\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x10\n" +
	"\x03eof\x18\x04 \x01(\bR\x03eof\"K\n" +
	"\x18UploadFileSecretResponse\x12/\n" +
	"\x06secret\x18\x01 \x01(\v2\x17.heimdall.v1.SecretMetaR\x06secret\"D\n" +
	"\x0fDownloadRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x02 \x01(\x05R\tchunkSize\"5\n" +
	"\rDownloadChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x10\n" +
	"\x03eof\x18\x02 \x01(\bR\x03eof\"&\n" +
	"\x10ExportKeyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x82\x01\n" +
	"\x11ExportKeyResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bkey_type\x18\x02 \x01(\tR\akeyType\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey\x12\x1f\n" +
	"\vprivate_key\x18\x04 \x01(\fR\n" +
	"privateKey\"\x15\n" +
	"\x13ListPasskeysRequest\"e\n" +
	"\vPasskeyMeta\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x120\n" +
	"\x14supports_hmac_secret\x18\x03 \x01(\bR\x12supportsHmacSecret\"L\n" +
	"\x14ListPasskeysResponse\x124\n" +
	"\bpasskeys\x18\x01 \x03(\v2\x18.heimdall.v1.PasskeyMetaR\bpasskeys\"5\n" +
	"\vForwardSpec\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x12\n" +
	"\x04spec\x18\x02 \x01(\tR\x04spec\"\x90\x02\n" +
	"\x12PlanConnectRequest\x12\x1b\n" +
	"\thost_name\x18\x01 \x01(\tR\bhostName\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12\x1d\n" +
	"\n" +
	"jump_hosts\x18\x04 \x03(\tR\tjumpHosts\x12\x1a\n" +
	"\bforwards\x18\x05 \x03(\tR\bforwards\x12#\n" +
	"\ridentity_path\x18\x06 \x01(\tR\fidentityPath\x12\x1f\n" +
	"\vknown_hosts\x18\a \x01(\tR\n" +
	"knownHosts\x12\x1b\n" +
	"\tprint_cmd\x18\b \x01(\bR\bprintCmd\x12\x17\n" +
	"\adry_run\x18\t \x01(\bR\x06dryRun\"\x8e\x01\n" +
	"\n" +
	"SSHCommand\x12\x16\n" +
	"\x06binary\x18\x01 \x01(\tR\x06binary\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12#\n" +
	"\rredacted_args\x18\x03 \x03(\tR\fredactedArgs\x12\x10\n" +
	"\x03env\x18\x04 \x03(\tR\x03env\x12\x1d\n" +
	"\n" +
	"temp_files\x18\x05 \x03(\tR\ttempFiles\"H\n" +
	"\x13PlanConnectResponse\x121\n" +
	"\acommand\x18\x01 \x01(\v2\x17.heimdall.v1.SSHCommandR\acommand\")\n" +
	"\x11ListEventsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"\xad\x01\n" +
	"\n" +
	"AuditEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x1f\n" +
	"\vtarget_type\x18\x03 \x01(\tR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x04 \x01(\tR\btargetId\x12\x16\n" +
	"\x06result\x18\x05 \x01(\tR\x06result\x12!\n" +
	"\fdetails_json\x18\x06 \x01(\tR\vdetailsJson\"E\n" +
	"\x12ListEventsResponse\x12/\n" +
	"\x06events\x18\x01 \x03(\v2\x17.heimdall.v1.AuditEventR\x06events\"\x15\n" +
	"\x13CreateBackupRequest\"2\n" +
	"\x14CreateBackupResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"S\n" +
	"\x19RecordSessionStartRequest\x12\x17\n" +
	"\ahost_id\x18\x01 \x01(\tR\x06hostId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\";\n" +
	"\x1aRecordSessionStartResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"U\n" +
	"\x17RecordSessionEndRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\"\x1a\n" +
	"\x18RecordSessionEndResponse\"i\n" +
	"\x16VerifyAssertionRequest\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x1b\n" +
	"\tauth_data\x18\x02 \x01(\fR\bauthData\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\")\n" +
	"\x17VerifyAssertionResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"9\n" +
	"\x17VerifyPassphraseRequest\x12\x1e\n" +
	"\n" +
	"passphrase\x18\x01 \x01(\tR\n" +
	"passphrase\"*\n" +
	"\x18VerifyPassphraseResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\x8e\x01\n" +
	"\fVaultService\x12A\n" +
	"\x06Status\x12\x1a.heimdall.v1.StatusRequest\x1a\x1b.heimdall.v1.StatusResponse\x12;\n" +
	"\x04Lock\x12\x18.heimdall.v1.LockRequest\x1a\x19.heimdall.v1.LockResponse2_\n" +
	"\x0eVersionService\x12M\n" +
	"\n" +
	"GetVersion\x12\x1e.heimdall.v1.GetVersionRequest\x1a\x1f.heimdall.v1.GetVersionResponse2Y\n" +
	"\vHostService\x12J\n" +
	"\tListHosts\x12\x1d.heimdall.v1.ListHostsRequest\x1a\x1e.heimdall.v1.ListHostsResponse2\xba\x03\n" +
	"\rSecretService\x12P\n" +
	"\vListSecrets\x12\x1f.heimdall.v1.ListSecretsRequest\x1a .heimdall.v1.ListSecretsResponse\x12Y\n" +
	"\x0eGetSecretValue\x12\".heimdall.v1.GetSecretValueRequest\x1a#.heimdall.v1.GetSecretValueResponse\x12S\n" +
	"\fDeleteSecret\x12 .heimdall.v1.DeleteSecretRequest\x1a!.heimdall.v1.DeleteSecretResponse\x12U\n" +
	"\x10UploadFileSecret\x12\x18.heimdall.v1.UploadChunk\x1a%.heimdall.v1.UploadFileSecretResponse(\x01\x12P\n" +
	"\x12DownloadFileSecret\x12\x1c.heimdall.v1.DownloadRequest\x1a\x1a.heimdall.v1.DownloadChunk0\x012X\n" +
	"\n" +
	"KeyService\x12J\n" +
	"\tExportKey\x12\x1d.heimdall.v1.ExportKeyRequest\x1a\x1e.heimdall.v1.ExportKeyResponse2e\n" +
	"\x0ePasskeyService\x12S\n" +
	"\fListPasskeys\x12 .heimdall.v1.ListPasskeysRequest\x1a!.heimdall.v1.ListPasskeysResponse2[\n" +
	"\x0eConnectService\x12I\n" +
	"\x04Plan\x12\x1f.heimdall.v1.PlanConnectRequest\x1a .heimdall.v1.PlanConnectResponse2]\n" +
	"\fAuditService\x12M\n" +
	"\n" +
	"ListEvents\x12\x1e.heimdall.v1.ListEventsRequest\x1a\x1f.heimdall.v1.ListEventsResponse2d\n" +
	"\rBackupService\x12S\n" +
	"\fCreateBackup\x12 .heimdall.v1.CreateBackupRequest\x1a!.heimdall.v1.CreateBackupResponse2\xd8\x01\n" +
	"\x0eSessionService\x12e\n" +
	"\x12RecordSessionStart\x12&.heimdall.v1.RecordSessionStartRequest\x1a'.heimdall.v1.RecordSessionStartResponse\x12_\n" +
	"\x10RecordSessionEnd\x12$.heimdall.v1.RecordSessionEndRequest\x1a%.heimdall.v1.RecordSessionEndResponse2\xce\x01\n" +
	"\rReauthService\x12\\\n" +
	"\x0fVerifyAssertion\x12#.heimdall.v1.VerifyAssertionRequest\x1a$.heimdall.v1.VerifyAssertionResponse\x12_\n" +
	"\x10VerifyPassphrase\x12$.heimdall.v1.VerifyPassphraseRequest\x1a%.heimdall.v1.VerifyPassphraseResponseB*Z(github.com/amanthanvi/heimdall/api/v1;v1b\x06proto3"

var (
	file_api_v1_heimdall_proto_rawDescOnce sync.Once
	file_api_v1_heimdall_proto_rawDescData []byte
)

func file_api_v1_heimdall_proto_rawDescGZIP() []byte {
	file_api_v1_heimdall_proto_rawDescOnce.Do(func() {
		file_api_v1_heimdall_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_heimdall_proto_rawDesc), len(file_api_v1_heimdall_proto_rawDesc)))
	})
	return file_api_v1_heimdall_proto_rawDescData
}

var file_api_v1_heimdall_proto_msgTypes = make([]protoimpl.MessageInfo, 42)
var file_api_v1_heimdall_proto_goTypes = []any{
	(*StatusRequest)(nil),              // 0: heimdall.v1.StatusRequest
	(*StatusResponse)(nil),             // 1: heimdall.v1.StatusResponse
	(*LockRequest)(nil),                // 2: heimdall.v1.LockRequest
	(*LockResponse)(nil),               // 3: heimdall.v1.LockResponse
	(*GetVersionRequest)(nil),          // 4: heimdall.v1.GetVersionRequest
	(*GetVersionResponse)(nil),         // 5: heimdall.v1.GetVersionResponse
	(*ListHostsRequest)(nil),           // 6: heimdall.v1.ListHostsRequest
	(*Host)(nil),                       // 7: heimdall.v1.Host
	(*ListHostsResponse)(nil),          // 8: heimdall.v1.ListHostsResponse
	(*ListSecretsRequest)(nil),         // 9: heimdall.v1.ListSecretsRequest
	(*SecretMeta)(nil),                 // 10: heimdall.v1.SecretMeta
	(*ListSecretsResponse)(nil),        // 11: heimdall.v1.ListSecretsResponse
	(*GetSecretValueRequest)(nil),      // 12: heimdall.v1.GetSecretValueRequest
	(*GetSecretValueResponse)(nil),     // 13: heimdall.v1.GetSecretValueResponse
	(*DeleteSecretRequest)(nil),        // 14: heimdall.v1.DeleteSecretRequest
	(*DeleteSecretResponse)(nil),       // 15: heimdall.v1.DeleteSecretResponse
	(*UploadChunk)(nil),                // 16: heimdall.v1.UploadChunk
	(*UploadFileSecretResponse)(nil),   // 17: heimdall.v1.UploadFileSecretResponse
	(*DownloadRequest)(nil),            // 18: heimdall.v1.DownloadRequest
	(*DownloadChunk)(nil),              // 19: heimdall.v1.DownloadChunk
	(*ExportKeyRequest)(nil),           // 20: heimdall.v1.ExportKeyRequest
	(*ExportKeyResponse)(nil),          // 21: heimdall.v1.ExportKeyResponse
	(*ListPasskeysRequest)(nil),        // 22: heimdall.v1.ListPasskeysRequest
	(*PasskeyMeta)(nil),                // 23: heimdall.v1.PasskeyMeta
	(*ListPasskeysResponse)(nil),       // 24: heimdall.v1.ListPasskeysResponse
	(*ForwardSpec)(nil),                // 25: heimdall.v1.ForwardSpec
	(*PlanConnectRequest)(nil),         // 26: heimdall.v1.PlanConnectRequest
	(*SSHCommand)(nil),                 // 27: heimdall.v1.SSHCommand
	(*PlanConnectResponse)(nil),        // 28: heimdall.v1.PlanConnectResponse
	(*ListEventsRequest)(nil),          // 29: heimdall.v1.ListEventsRequest
	(*AuditEvent)(nil),                 // 30: heimdall.v1.AuditEvent
	(*ListEventsResponse)(nil),         // 31: heimdall.v1.ListEventsResponse
	(*CreateBackupRequest)(nil),        // 32: heimdall.v1.CreateBackupRequest
	(*CreateBackupResponse)(nil),       // 33: heimdall.v1.CreateBackupResponse
	(*RecordSessionStartRequest)(nil),  // 34: heimdall.v1.RecordSessionStartRequest
	(*RecordSessionStartResponse)(nil), // 35: heimdall.v1.RecordSessionStartResponse
	(*RecordSessionEndRequest)(nil),    // 36: heimdall.v1.RecordSessionEndRequest
	(*RecordSessionEndResponse)(nil),   // 37: heimdall.v1.RecordSessionEndResponse
	(*VerifyAssertionRequest)(nil),     // 38: heimdall.v1.VerifyAssertionRequest
	(*VerifyAssertionResponse)(nil),    // 39: heimdall.v1.VerifyAssertionResponse
	(*VerifyPassphraseRequest)(nil),    // 40: heimdall.v1.VerifyPassphraseRequest
	(*VerifyPassphraseResponse)(nil),   // 41: heimdall.v1.VerifyPassphraseResponse
}
var file_api_v1_heimdall_proto_depIdxs = []int32{
	7,  // 0: heimdall.v1.ListHostsResponse.hosts:type_name -> heimdall.v1.Host
	10, // 1: heimdall.v1.ListSecretsResponse.secrets:type_name -> heimdall.v1.SecretMeta
	10, // 2: heimdall.v1.UploadFileSecretResponse.secret:type_name -> heimdall.v1.SecretMeta
	23, // 3: heimdall.v1.ListPasskeysResponse.passkeys:type_name -> heimdall.v1.PasskeyMeta
	27, // 4: heimdall.v1.PlanConnectResponse.command:type_name -> heimdall.v1.SSHCommand
	30, // 5: heimdall.v1.ListEventsResponse.events:type_name -> heimdall.v1.AuditEvent
	0,  // 6: heimdall.v1.VaultService.Status:input_type -> heimdall.v1.StatusRequest
	2,  // 7: heimdall.v1.VaultService.Lock:input_type -> heimdall.v1.LockRequest
	4,  // 8: heimdall.v1.VersionService.GetVersion:input_type -> heimdall.v1.GetVersionRequest
	6,  // 9: heimdall.v1.HostService.ListHosts:input_type -> heimdall.v1.ListHostsRequest
	9,  // 10: heimdall.v1.SecretService.ListSecrets:input_type -> heimdall.v1.ListSecretsRequest
	12, // 11: heimdall.v1.SecretService.GetSecretValue:input_type -> heimdall.v1.GetSecretValueRequest
	14, // 12: heimdall.v1.SecretService.DeleteSecret:input_type -> heimdall.v1.DeleteSecretRequest
	16, // 13: heimdall.v1.SecretService.UploadFileSecret:input_type -> heimdall.v1.UploadChunk
	18, // 14: heimdall.v1.SecretService.DownloadFileSecret:input_type -> heimdall.v1.DownloadRequest
	20, // 15: heimdall.v1.KeyService.ExportKey:input_type -> heimdall.v1.ExportKeyRequest
	22, // 16: heimdall.v1.PasskeyService.ListPasskeys:input_type -> heimdall.v1.ListPasskeysRequest
	26, // 17: heimdall.v1.ConnectService.Plan:input_type -> heimdall.v1.PlanConnectRequest
	29, // 18: heimdall.v1.AuditService.ListEvents:input_type -> heimdall.v1.ListEventsRequest
	32, // 19: heimdall.v1.BackupService.CreateBackup:input_type -> heimdall.v1.CreateBackupRequest
	34, // 20: heimdall.v1.SessionService.RecordSessionStart:input_type -> heimdall.v1.RecordSessionStartRequest
	36, // 21: heimdall.v1.SessionService.RecordSessionEnd:input_type -> heimdall.v1.RecordSessionEndRequest
	38, // 22: heimdall.v1.ReauthService.VerifyAssertion:input_type -> heimdall.v1.VerifyAssertionRequest
	40, // 23: heimdall.v1.ReauthService.VerifyPassphrase:input_type -> heimdall.v1.VerifyPassphraseRequest
	1,  // 24: heimdall.v1.VaultService.Status:output_type -> heimdall.v1.StatusResponse
	3,  // 25: heimdall.v1.VaultService.Lock:output_type -> heimdall.v1.LockResponse
	5,  // 26: heimdall.v1.VersionService.GetVersion:output_type -> heimdall.v1.GetVersionResponse
	8,  // 27: heimdall.v1.HostService.ListHosts:output_type -> heimdall.v1.ListHostsResponse
	11, // 28: heimdall.v1.SecretService.ListSecrets:output_type -> heimdall.v1.ListSecretsResponse
	13, // 29: heimdall.v1.SecretService.GetSecretValue:output_type -> heimdall.v1.GetSecretValueResponse
	15, // 30: heimdall.v1.SecretService.DeleteSecret:output_type -> heimdall.v1.DeleteSecretResponse
	17, // 31: heimdall.v1.SecretService.UploadFileSecret:output_type -> heimdall.v1.UploadFileSecretResponse
	19, // 32: heimdall.v1.SecretService.DownloadFileSecret:output_type -> heimdall.v1.DownloadChunk
	21, // 33: heimdall.v1.KeyService.ExportKey:output_type -> heimdall.v1.ExportKeyResponse
	24, // 34: heimdall.v1.PasskeyService.ListPasskeys:output_type -> heimdall.v1.ListPasskeysResponse
	28, // 35: heimdall.v1.ConnectService.Plan:output_type -> heimdall.v1.PlanConnectResponse
	31, // 36: heimdall.v1.AuditService.ListEvents:output_type -> heimdall.v1.ListEventsResponse
	33, // 37: heimdall.v1.BackupService.CreateBackup:output_type -> heimdall.v1.CreateBackupResponse
	35, // 38: heimdall.v1.SessionService.RecordSessionStart:output_type -> heimdall.v1.RecordSessionStartResponse
	37, // 39: heimdall.v1.SessionService.RecordSessionEnd:output_type -> heimdall.v1.RecordSessionEndResponse
	39, // 40: heimdall.v1.ReauthService.VerifyAssertion:output_type -> heimdall.v1.VerifyAssertionResponse
	41, // 41: heimdall.v1.ReauthService.VerifyPassphrase:output_type -> heimdall.v1.VerifyPassphraseResponse
	24, // [24:42] is the sub-list for method output_type
	6,  // [6:24] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_v1_heimdall_proto_init() }
func file_api_v1_heimdall_proto_init() {
	if File_api_v1_heimdall_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_heimdall_proto_rawDesc), len(file_api_v1_heimdall_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   42,
			NumExtensions: 0,
			NumServices:   11,
		},
		GoTypes:           file_api_v1_heimdall_proto_goTypes,
		DependencyIndexes: file_api_v1_heimdall_proto_depIdxs,
		MessageInfos:      file_api_v1_heimdall_proto_msgTypes,
	}.Build()
	File_api_v1_heimdall_proto = out.File
	file_api_v1_heimdall_proto_goTypes = nil
	file_api_v1_heimdall_proto_depIdxs = nil
}
